apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: demo-account-us-east-1
  uuid: 78092fe1-d6a0-4028-9594-ae419f811c82
spec:
  source: /bundles/example.com/region/v1
  inputs:
    account: demo-account
    region: us-east-1
environments:
  stg: {}
