apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: demo-ecs-cluster
  uuid: 5de03a97-0509-431f-a786-eb632a2bd66d
spec:
  source: /bundles/example.com/tf-aws-complete-ecs-fargate-cluster/v1
  inputs:

    # tmdoc: The name for the ECS Fargate Cluster, Load Balancer, and VPC.
    name: demo-ecs-cluster

    # tmdoc: CIDR block for the VPC (e.g., 10.0.0.0/16)
    vpc_cidr: 10.10.0.0/16

    # tmdoc: AWS Resource tags to attach to all created resources. Additional internal tags will be added by default.
    tags: {}
environments:
  dev: {}
