apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: terramat-catalyst-demo-bucket
  uuid: 0a39e30a-31e5-40da-90e8-e683489758d5
spec:
  source: /bundles/example.com/tf-aws-s3/v1
  inputs:

    # tmdoc: A globally unique name of the S3 bucket; it will be suffxed with the current `-{environment}`
    name: terramat-catalyst-demo-bucket

    # tmdoc: Whether the bucket should be private or public
    visibility: private

    # tmdoc: A map to control sources and versions of underlying Terraform Modules used in generated code by underlying components.
    # tmdoc:
    # tmdoc: The key of the map is the terraform registry ID of the module.
    # tmdoc:
    # tmdoc: Available keys:
    # tmdoc:   - terraform-aws-modules/s3-bucket/aws
    terraform_modules:
      terraform-aws-modules/s3-bucket/aws:
        source: terraform-aws-modules/s3-bucket/aws
        version: 5.9.1
environments:
  prd: {}
  stg:
    inputs:
      visibility: public-read-write
