apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: ecs-fargate-dev-dev
  uuid: 8d3d9fdc-e259-4a5c-80fe-cde16193fc6a
spec:
  source: /bundles/example.com/tf-aws-complete-ecs-fargate-cluster/v1
  inputs:
    
    # A list of available environments to create the ECS cluster in.
    env: dev
    
    # The name for the ECS Fargate Cluster, Load Balancer, and VPC.
    name: ecs-fargate-dev
    
    # CIDR block for the VPC (e.g., 10.0.0.0/16)
    vpc_cidr: 10.0.0.0/16
    
    # AWS Resource tags to attach to all created resources. Additional internal tags will be added by default.
    tags: {}
