apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: my-application-a
  uuid: ed555bd3-c56e-4415-8b38-e27fb9ec75ee
spec: {}
environments:
  dev:
    source: /bundles/example.com/tf-aws-ecs-fargate-service/v1
    inputs:
      # tmdoc: Name of the ECS Fargate service
      service_name: My Application A
      # tmdoc: The ECS cluster to attach this service to
      cluster: my-cluster
      # tmdoc: Docker image URI for the main container
      container_image: nginx
