apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: my-nginx
  uuid: a2356afb-0e6f-4dcb-b209-67cd2c25c2a6
spec:
  source: /bundles/example.com/tf-aws-ecs-fargate-service/v1
  inputs:
    
    # tmdoc: Name of the ECS Fargate service
    service_name: my-nginx
    
    # tmdoc: Bundle UUID of the ECS cluster to attach this service to
    cluster_slug: my-cluster
    
    # tmdoc: Name of the main container
    container_name: app
    
    # tmdoc: Port that containers will listen on
    container_port: 3000
    
    # tmdoc: Docker image URI for the main container
    container_image: nginx
    
    # tmdoc: CPU units for the task (1024 = 1 vCPU)
    cpu: 1024
    
    # tmdoc: Memory for the task in MB
    memory: 4096
    
    # tmdoc: Path pattern on the ALB listener to route to this service (e.g., /api/*)
    path_pattern: /my-nginx/*
    
    # tmdoc: Key/name of the target group in the ALB (e.g., 'http', 'ex_ecs')
    target_group_key: http
environments:
  dev: {}
